version: 1.2
workflows:

  - name: FastQsToGvcf
    subclass: WDL
    primaryDescriptorPath: /pipelines/kidlab/FastQsToGvcf.wdl

  - name: GvcfToCohortVcf
    subclass: WDL
    primaryDescriptorPath: /pipelines/kidlab/GvcfToCohortVcf.wdl

  - name: FilterFamily
    subclass: WDL
    primaryDescriptorPath: /pipelines/kidlab/FilterFamily.wdl

  - name: AnnoCohort
    subclass: WDL
    primaryDescriptorPath: /pipelines/kidlab/AnnoCohort.wdl
