version: 1.2
workflows:

  - name: FastQsToGvcf
    subclass: WDL
    primaryDescriptorPath: /pipelines/kidlab/FastQsToGvcf.wdl

  - name: AnnoFamily
    subclass: WDL
    primaryDescriptorPath: /pipelines/kidlab/AnnoFamily.wdl
